apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: multi-server
        image: cygnetops/multi-server-pgfix-5-11
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: "5432"
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgress-pass
                key: PGPASSWORD
                
          

